name: phylotreeminer-env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  
  - python=3.10
  
  - pdoc3
  - biopython
  - dendropy
  - mlxtend
  - pandas
  - numpy
  - tqdm
  - matplotlib
  - neo4j
  - fastapi
  - uvicorn[standard]
  - owid-catalog
  - aiofiles
  
  - mafft
  - clustalo
  - iqtree
  - raxml-ng
  - fasttree
  - mrbayes